config/routes.rb
Nanomedicine::Application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    resources :news, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :events, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :members, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
      get ':id/page/:page', :action => :show, :on => :collection
    end
    resources :publications, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end

    get "home/index"
    get "home/contact"
    get "search/results"

    root :to => 'home#index'

    devise_for :members, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @query = params[:search]
    if not @query.nil? || @query.empty?
      @members = Member.search(lastname_or_firstname_cont: @query).result.order(:lastname)
      @publications = Publication.search(title_cont: @query).result.order(:title)
      @n = @members.count + @publications.count
    else
      @n=0
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_member.html.haml
%li
  = link_to "#{member.firstname} #{member.lastname}", member_path(member)

app/views/search/_publication.html.haml
%li
  %h6="#{publication.title} #{publication.year}"

app/views/search/results.html.haml
- content_for :page_title, "search"
#main-content
  %h3= t(:search_results)
  - if @n.nil? || @query.nil?
    = t(:empty_search)
  - elsif @n == 0
    = "There is no result for the query \"#{@query.html_safe}\"."
  - else
    = "The query was \"#{@query.html_safe}\", #{@n} results match."
    - if not @members.empty?
      %h4= t(:members)
      %ul
        = render partial: "member", collection: @members
    - if not @publications.empty?
      %h4= t(:publications)
      %ul
        = render partial: "publication", collection: @publications