config/routes.rb
Nanomedicine::Application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    resources :news, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :events, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :members, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
      get ':id/page/:page', :action => :show, :on => :collection
    end
    resources :publications, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end

    get "home/index"
    get "home/contact"
    get "search/results"

    root :to => 'home#index'

    devise_for :members, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
  end

end

app/views/shared/_footer.html.haml
%footer#footer
  #footer-container
    #copyright
      nanomedicinelaboratory.com © all rights reserved
    = render partial: "shared/nav"

app/views/shared/_header.html.haml
%header
  = render partial: "shared/menubar"
  #titlebar
    #titlebar_container
      -# = image_tag "nanomedicine_logo.png", alt: "nanomedicinelab"
      #logo
  %nav
    #nav_container
      = render partial: "shared/nav"
      = form_tag url_for( controller: :search, action: :results), method: :get, class: "navbar-search", turboboost:true do 
        = text_field_tag 'search', nil, placeholder: t(:search)
  %div
    = render partial: "shared/messages"

app/views/shared/_menubar.html.haml
#menubar
  #language_select
    %ul#lang
      %li
        = link_to "en", :locale=>'en'
      %li
        = link_to "fr", :locale=>'fr'  
  #login
    %ul#login_controls
      -if member_signed_in?
        %li= link_to t(:logout), destroy_member_session_path, method: :delete
      -else
        %li= link_to t(:login), new_member_session_path
      -if member_signed_in?
        %li= link_to t(:manage_profile), edit_member_registration_path
      -else
        %li= link_to t(:signup), new_member_registration_path

app/views/shared/_messages.html.haml
- flash.each do |name,msg|
  -if msg.is_a?(String)
    =content_tag :div, msg, id: "flash_#{name}"

app/views/shared/_nav.html.haml
%ul
  %li
    = link_to t(:home), controller: "/home", action: "index"
  %li
    = link_to t(:news), news_index_path
  %li
    = link_to t(:members), members_path
  %li
    = link_to t(:publications), publications_path
  %li
    = link_to t(:events), events_path
  %li
    = link_to t(:contact_us), controller: "/home", action: "contact"