config/routes.rb
Nanomedicine::Application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    resources :news, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :events, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end
    resources :members, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
      get ':id/page/:page', :action => :show, :on => :collection
    end
    resources :publications, only: [:index, :show] do
      get 'page/:page', :action => :index, :on => :collection
    end

    get "home/index"
    get "home/contact"
    get "search/results"

    root :to => 'home#index'

    devise_for :members, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  before_save :destroy_image?

  attr_accessor :delete_image

  has_attached_file :image,
                    styles: {medium: "150x150>"},
                    url: "/images/news/:id/:basename.:extension"
  validates :image, attachment_content_type: { content_type: /\Aimage\/.*\Z/ }
  validates :title, presence: true
  validates :content, presence: true
  validates :date, presence: true

  private

  def destroy_image?
    if delete_image == "1"
      image.clear
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.order(:date).page(params[:page])
  end
  def show
    @n = News.find(params[:id])
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_news.html.haml
%li
  %h6= link_to n.title, news_path(n)
  %p.subtitle= l(n.date, format: :day_and_month)
  %p= n.content

app/views/news/index.html.haml
- content_for :page_title, t(:news)
#main-content
  %h3= t(:news)
  %ul
    - @news.each do |n|
      = render partial: "news", locals: {n: n}
  = paginate @news

app/views/news/show.html.haml
- content_for :page_title, t(:news)
#main-content.single_column
  %h3= @n.title
  %p= @n.date
  %p= @n.content